// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PeminjamanRuangan.Api.Data;

#nullable disable

namespace PeminjamanRuangan.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209105916_AddPeminjamanCrud")]
    partial class AddPeminjamanCrud
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PeminjamanRuangan.Api.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Keperluan")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keperluan");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nama_peminjam");

                    b.Property<int>("RuanganId")
                        .HasColumnType("integer")
                        .HasColumnName("ruangan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TanggalPinjam")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tanggal_pinjam");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tanggal_selesai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RuanganId");

                    b.ToTable("peminjaman");
                });

            modelBuilder.Entity("PeminjamanRuangan.Api.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("integer")
                        .HasColumnName("kapasitas");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lokasi");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nama_ruangan");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NamaRuangan")
                        .IsUnique();

                    b.ToTable("ruangan");
                });

            modelBuilder.Entity("PeminjamanRuangan.Api.Models.Peminjaman", b =>
                {
                    b.HasOne("PeminjamanRuangan.Api.Models.Ruangan", "Ruangan")
                        .WithMany("Peminjaman")
                        .HasForeignKey("RuanganId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruangan");
                });

            modelBuilder.Entity("PeminjamanRuangan.Api.Models.Ruangan", b =>
                {
                    b.Navigation("Peminjaman");
                });
#pragma warning restore 612, 618
        }
    }
}
